spring:
  application:
    name: poke-aggregator
server:
  port: 8088
#resilience4j.ratelimiter:
#  instances:
#    review-service:
#      limitRefreshPeriod: 20s
#      limitForPeriod: 3
#      timeoutDuration: 0s
#
#resilience4j.circuitbreaker:
#  configs:
#    default:
#      slidingWindowSize: 20
#      registerHealthIndicator: true
#      # Failure rate threshold percentage
#      failureRateThreshold: 10
#      # Minimum number of call attempts before rate threshold percentage is checked.
#      ringBufferSizeInClosedState: 10
#      # How long to wait until switching to half open.
#      waitDurationInOpenState: 3s
#      # Number of successful requests before moving back to closed from half open.
#      ringBufferSizeInHalfOpenState: 5
#        # Exceptions that do not count towards opening the circuit.
#        #ignoreExceptions:
#        # Ignore 4xx exceptions.
#      #- org.springframework.web.client.HttpClientErrorException
#      instances:
#        review-service:
#          baseConfig: default

retry:
  maxAttempts: 1
  fixedDelay: 5


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 4
      minimumNumberOfCalls: 2
      failureRateThreshold: 50
      # How long to wait until switching to half open.
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 2
      recordExceptions:
        - org.springframework.web.reactive.function.client.WebClientResponseException
    instances:
      review-service:
        baseConfig: default