spring:
  application:
    name: poke-aggregator
  retry:
    max-attempts: 3
    backoff:
      delay: 100ms
      max-delay: 1000ms
      multiplier: 2.0
server:
  port: 8088
#resilience4j.ratelimiter:
#  instances:
#    review-service:
#      limitRefreshPeriod: 20s
#      limitForPeriod: 3
#      timeoutDuration: 0s
#
#resilience4j.circuitbreaker:
#  configs:
#    default:
#      slidingWindowSize: 20
#      registerHealthIndicator: true
#      # Failure rate threshold percentage
#      failureRateThreshold: 10
#      # Minimum number of call attempts before rate threshold percentage is checked.
#      ringBufferSizeInClosedState: 10
#      # How long to wait until switching to half open.
#      waitDurationInOpenState: 3s
#      # Number of successful requests before moving back to closed from half open.
#      ringBufferSizeInHalfOpenState: 5
#        # Exceptions that do not count towards opening the circuit.
#        #ignoreExceptions:
#        # Ignore 4xx exceptions.
#      #- org.springframework.web.client.HttpClientErrorException
#      instances:
#        review-service:
#          baseConfig: default

retry:
  maxAttempts: 3
  fixedDelay: 5


resilience4j:
  circuitbreaker:
    instances:
      review-service:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        maxWaitDurationOfCallHalfOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 4
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.util.concurrent.TimeoutException
#        automaticTransactionFromOpenToHalfOpenEnable: false
#        ignoreExceptions:
#          - org

logging:
  level:
    io.github.resilience4j: DEBUG
    root: DEBUG
security:
  ids:
    salt: 'this is my salt'
    patterns:
      - '.*Id$'
      - '.*id$'
      - '.*Uid$'
#ConcurrentHashMap
